"""Tablas iniciales

Revision ID: dcdfc6fc9694
Revises: 
Create Date: 2025-05-18 00:08:13.328683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcdfc6fc9694'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('modelo_carro', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('es_producto_nuevo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('resultados_comparativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('mae', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('rmse', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('reduccion_inventario_excedente', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('incremento_ventas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('stock_actual', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('stock_optimo', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=100), nullable=True),
    sa.Column('ultima_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predicciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_predicha', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('confianza', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fecha_prediccion', sa.DateTime(), nullable=True),
    sa.Column('modelo_version', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_venta', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ventas')
    op.drop_table('predicciones')
    op.drop_table('inventario')
    op.drop_table('usuarios')
    op.drop_table('resultados_comparativos')
    op.drop_table('productos')
    # ### end Alembic commands ###
